implemented contact list and contact details
toshanik/Homework_65apps pull request #3
Opened 2021-03-09 09:56 UTC by toshanik

Добавлены список контактов и контактная информация
colorPrimary = #58f3d8
colorPrimaryDark = colorPrimary
colorAccent = #b2cdef

![PDP_wcTAr3o](https://user-images.githubusercontent.com/62071098/110452994-2c0c5480-80df-11eb-9be8-c645f7526d62.jpg)

![iTzpctlDiw0](https://user-images.githubusercontent.com/62071098/110453007-2f074500-80df-11eb-8240-c92877324653.jpg)

2021-03-10 09:56 UTC, KalimullinIlnaz commented
Привет, теперь я буду твоим ревьюевором всегда, назначай меня обязательным ревьювером на каждый пулл реквест

2021-03-10 16:47 UTC, KalimullinIlnaz requested changes

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/java/com/nik/ant38/ContactDetailsFragment.kt
> +        return inflater.inflate(R.layout.fragment_contact_details, container, false)
этот инфлетинг можно вынести на уровне наследования класса, то есть 
`class ContactDetailsFragment : Fragment(R.layout.fragment_contact_details) `
и следовательно не нужно будет переопрделять этот метод

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/java/com/nik/ant38/ContactDetailsFragment.kt
> +private const val CONTACT_ID = "CONTACT_ID"
константу в компаньён объект перенеси

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/java/com/nik/ant38/ContactClickListener.kt
> +    fun onClickFragment(id: Int)
сделай id стрингом в дальнейшем понадобится + возможно id будет выходить за границы диапозона инт-а

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/java/com/nik/ant38/ContactListFragment.kt
> +        return inflater.inflate(R.layout.fragment_contact_list, container, false)
аналогично перенеси на уровнь объявления класса

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/java/com/nik/ant38/MainActivity.kt
> +            supportFragmentManager
вынеси этот код в отдельный метод и дай понятное название, типо открыть лист контактов или навиция на лист контактов

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/java/com/nik/ant38/MainActivity.kt
> +    override fun onClickFragment(id: Int) {
здесь также нужно сменить название, что то в стиле навигация на детали контакта

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
линеяр лаяут здесь можно убрать

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +            android:layout_marginStart="8dp"
все эти размеры перенеси в файл dimens.xml

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +            android:layout_marginStart="10dp"
аналогично здесь и в других местах

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_list.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
аналогично избавься от линеяра, вложенность лаяутов увеличивает время и затраты на отрисовку вью

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_list.xml
> +            android:layout_marginBottom="10dp"
можно заменить на margin_vertical

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_list.xml
> +    android:id="@+id/ContactListRootLayout"
id нужно давать в сamel case, то есть сontactListRootLayout

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:id="@+id/ConstraintLayout"
аналогично здесь и в остальных местах

2021-03-10 16:47 UTC, KalimullinIlnaz commented on app/src/main/java/com/nik/ant38/ContactListFragment.kt
> +    private var layout: View? = null
дай более понятное название этой переменной

2021-03-10 16:48 UTC, KalimullinIlnaz commented
и ещё похоже я не являюсь collaborators в твоем репозитории, перепроверь пожалуйста и если что добавь

2021-03-10 17:18 UTC, toshanik commented on app/src/main/java/com/nik/ant38/ContactDetailsFragment.kt
> +        return inflater.inflate(R.layout.fragment_contact_details, container, false)
Я не знаю как ответить вам иначе, поэтому напишу сюда.
Я отправлял вам заявку в collaborators, но вы ее еще не приняли. У меня висит Awaiting KalimullinIlnaz’s response

2021-03-10 17:25 UTC, KalimullinIlnaz commented on app/src/main/java/com/nik/ant38/ContactDetailsFragment.kt
> +        return inflater.inflate(R.layout.fragment_contact_details, container, false)
а, да, c телефона 404 выдавало, с компа норм - принял

2021-03-16 11:08 UTC, toshanik commented on app/src/main/res/layout/fragment_contact_details.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Мне его заменить на constraint layout?

2021-03-16 14:04 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Вообще удалить, лишняя обертка

2021-03-16 19:41 UTC, KalimullinIlnaz requested changes

2021-03-16 19:41 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:layout_marginStart="@dimen/horizontal_gap"
что значит gap? напиши конкретно какой там размер типо margin_20dp

2021-03-16 19:41 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:layout_marginStart="@dimen/horizontal_gap"
аналогично везде

2021-03-17 04:45 UTC, KalimullinIlnaz approved these changes

2021-03-17 07:18 UTC, KalimullinIlnaz reviewed
Нужно засквошить эти три коммита водин

2021-03-18 16:39 UTC, merged